### ISSUE TITLE
Does gr-tssynch blocks non-synchronous TS packets?

### ISSUE THREAD

**Issue by VDelport** [drmpeg/gr-tssync#2]
First of all, sorry for asking this question in an issue.

Is it correct that gr-tssync not only indicates whether the synchronization in successive TS packets has been lost (lack of sync byte 0x47), but also that gr-tssync only allows synchronous TS packets to pass through?

If so, how many bytes are lost if the synchronization is not correct for two consecutive TS packets?

**Comment by drmpeg** [comment]
No problem on asking questions here. The block will discard bytes after a loss of sync until the next sync byte is detected.

How many bytes are lost depends on the exact sequence of missing sync bytes. If the sync byte occurs one byte early, then you could lose 187 bytes. If the sync byte is one byte late, you'll only lose 1 byte. If many sync bytes are missing, you could lose an unlimited number of bytes.

**Comment by VDelport** [comment]
Thank you for your quick reply.

gr-tssync is a simple and efficient block that is absolutely necessary for my GNU radio radio system (single carrier system with a QPSK, no DVB-S/T). I transmit a TS packet stream with embedded IP/UDP packets and pass the data stream after the radio receiver to TSDuck's tsp. Unfortunately, tsp stops when a synchronization error occurs. This problem can be solved very well with gr-tssync. :)
