### ISSUE TITLE
cmake does not find the Gnu Radio Runtime

### ISSUE THREAD

**Issue by VDelport** [drmpeg/gr-tssync#3]
After cmake ../ I get the following error message:
- Boost version: 1.65.1
- Found the following Boost libraries:
- filesystem
- system
Checking for GNU Radio Module: RUNTIME
  * INCLUDES = GNURADIO_RUNTIME_INCLUDE_DIRS-NOTFOUND
  * LIBS = GNURADIO_RUNTIME_LIBRARIES_gnuradio-runtime-NOTFOUND; GNURADIO_RUNTIME_LIBRARIES_gnuradio-pmt-NOTFOUND; GNURADIO_RUNTIME_LIBRARIES_log4cpp-NOTFOUND
- Could NOT find GNURADIO_RUNTIME (missing: GNURADIO_RUNTIME_LIBRARIES GNURADIO_RUNTIME_INCLUDE_DIRS)
GNURADIO_RUNTIME_FOUND = FALSE
CMake Error at /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake:114 (message):
   Required GNU Radio Component: RUNTIME missing!
Call stack (most recent call first):
   /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake:121

Do you have any idea how to fix the problem?

**Comment by drmpeg** [comment]
Your GNU Radio install looks broken. How did you install GNU Radio?

**Comment by VDelport** [comment]
Yes you are absolutely right, I have now run out
sudo apt-get install gnuradio-dev
and everything is fine. Sorry for the question.
